# Generated by Django 5.1 on 2024-09-13 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('church', models.CharField(max_length=250, null=True)),
                ('district', models.CharField(max_length=250, null=True)),
                ('dimes', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('period', models.DateField(max_length=250, null=True)),
                ('reference', models.CharField(max_length=250, null=True)),
                ('datereg', models.DateField(null=True)),
                ('montant', models.FloatField()),
                ('ref', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eds', models.FloatField(null=True)),
                ('prosperity', models.FloatField(null=True)),
                ('aniversary', models.FloatField(null=True)),
                ('worship', models.FloatField(null=True)),
                ('federation', models.FloatField(null=True)),
                ('mondial', models.FloatField(null=True)),
                ('special', models.FloatField(null=True)),
                ('frais', models.FloatField(null=True)),
                ('entree', models.FloatField(null=True)),
                ('sortie', models.FloatField(null=True)),
                ('recap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='treasure.recap')),
            ],
        ),
    ]
