# Generated by Django 5.1 on 2024-09-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('church', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('dimes', models.FloatField()),
                ('total', models.FloatField()),
                ('period', models.DateField(max_length=250)),
                ('reference', models.CharField(max_length=250)),
                ('datereg', models.DateField()),
                ('montant', models.FloatField()),
                ('ref', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
